// @ts-check
/**
 * E2E test: driver registration document upload flow with large photos
 *
 * Verifies that the XHR-based doRegister() path:
 *   1. Shows the #upload-progress-screen overlay
 *   2. Advances the progress bar to 100 %
 *   3. Hides the overlay after the server responds
 *   4. Shows the driver app (#app visible, #auth-screen hidden)
 *   5. Shows the pending-approval card (new drivers always get accountStatus:'pending')
 *
 * POST /api/auth/register is intercepted so the test is fully self-contained —
 * no MongoDB credentials are required.  The server must be reachable to serve
 * driver.html and its assets (playwright.config.js starts it automatically).
 *
 * Run:  cd ride-hailing && npx playwright test
 */

const { test, expect } = require('@playwright/test');
const path = require('path');

// ── Test fixtures ─────────────────────────────────────────────────────────────
// Large plasma-fractal JPEGs (~1.7 MB each) generated by:
//   magick -size 2500x1900 plasma:fractal -quality 92 <name>.jpg
const FIXTURES = {
  profile:   path.join(__dirname, 'fixtures', 'profile.jpg'),
  license:   path.join(__dirname, 'fixtures', 'license.jpg'),
  cnicFront: path.join(__dirname, 'fixtures', 'cnic-front.jpg'),
  cnicBack:  path.join(__dirname, 'fixtures', 'cnic-back.jpg'),
};

// ── Mock registration response ────────────────────────────────────────────────
// Mimics the shape returned by POST /api/auth/register so that saveSession()
// and bootApp() run exactly as they would with a real server response.
const MOCK_REGISTER_RESPONSE = {
  token: [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',
    'eyJpZCI6IjY2MDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsInJvbGUiOiJkcml2ZXIiLCJuYW1lIjoiVGVzdCBEcml2ZXIifQ',
    'FAKESIGNATURE',
  ].join('.'),
  sessionToken: 'fakesessiontoken1234567890abcdef',
  user: {
    id:            '660000000000000000000000',
    name:          'Test Driver',
    email:         '',
    phone:         '+923001234999',
    role:          'driver',
    accountStatus: 'pending',   // new drivers always start as pending
    vehicleType:   'Car Mini',
    vehicleModel:  'Suzuki Cultus 2020',
    vehiclePlate:  'LHR-9999',
    lastDailyFeePaidAt: null,
    dailyFeeAmount: 200,
  },
};

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Intercept the register API and silence unrelated boot-time requests.
 *
 * IMPORTANT: the socket.io *client JS file* must load so that `io` is defined
 * when connectSocket() runs inside bootApp().  Only socket.io connection/
 * polling requests are aborted.
 */
async function setupRoutes(page, delay = 250) {
  await page.route('**/api/auth/register', async (route) => {
    await new Promise((r) => setTimeout(r, delay));
    await route.fulfill({
      status: 201,
      contentType: 'application/json',
      body: JSON.stringify(MOCK_REGISTER_RESPONSE),
    });
  });

  // Allow the socket.io *script* to load; abort only connection requests.
  await page.route('**/socket.io/**', (route) => {
    if (route.request().url().endsWith('.js')) {
      route.continue();
    } else {
      route.abort();   // server will also reject the fake JWT on connect_error
    }
  });

  // Stub boot-time API calls so they resolve cleanly without touching the DB.
  await page.route('**/api/auth/me', (route) =>
    route.fulfill({ status: 401, contentType: 'application/json', body: '{"error":"unauthorized"}' })
  );
  await page.route('**/api/wallet**', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: '{"balance":0,"transactions":[]}' })
  );
  await page.route('**/api/rides/my**', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: '[]' })
  );
  await page.route('**/api/settings/payment**', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: '{"accounts":{}}' })
  );
  await page.route('**/api/support/**', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: '[]' })
  );
}

/** Fill Step 1 of the registration form and advance to Step 2. */
async function fillStep1(page, { phone = '+923001234999' } = {}) {
  await page.getByRole('button', { name: 'Register' }).click();
  await expect(page.locator('#register-form')).toBeVisible();

  await page.locator('#r-name').fill('Test Driver');
  await page.locator('#r-phone').fill(phone);
  await page.locator('#r-pass').fill('password123');
  await page.locator('#r-vehicle').selectOption('Car Mini');
  await page.locator('#r-vehicle-model').fill('Suzuki Cultus 2020');
  await page.locator('#r-plate').fill('LHR-9999');

  await page.getByRole('button', { name: /Continue.*Upload Documents/i }).click();
  await expect(page.locator('#reg-step2')).toBeVisible();
}

/** Attach the four large test-fixture photos to the file inputs. */
async function uploadPhotos(page) {
  await page.locator('#r-profile-photo').setInputFiles(FIXTURES.profile);
  await page.locator('#r-license-photo').setInputFiles(FIXTURES.license);
  await page.locator('#r-cnic-front').setInputFiles(FIXTURES.cnicFront);
  await page.locator('#r-cnic-back').setInputFiles(FIXTURES.cnicBack);
}

// ── Tests ─────────────────────────────────────────────────────────────────────

test.describe('Document upload flow — large photos (~1.7 MB each)', () => {
  test.beforeEach(async ({ page }) => {
    await setupRoutes(page);
    await page.goto('/driver');
  });

  // ---------------------------------------------------------------------------
  test(
    'upload progress overlay appears, reaches 100 %, hides, and driver app loads',
    async ({ page }) => {
      await fillStep1(page);
      await uploadPhotos(page);

      // ── Submit ──────────────────────────────────────────────────────────
      await page.locator('#reg-submit-btn').click();

      // ── Assert 1: upload-progress overlay becomes visible ───────────────
      const overlay = page.locator('#upload-progress-screen');
      await expect(overlay).toBeVisible({ timeout: 8_000 });

      // ── Assert 2: progress bar reaches 100 % ────────────────────────────
      // xhr.onload sets the bar to 100 % on a 2xx response.
      await expect(page.locator('#upload-progress-pct')).toHaveText('100%', { timeout: 15_000 });

      const barWidth = await page.locator('#upload-progress-bar').evaluate(
        (el) => el.style.width
      );
      expect(barWidth).toBe('100%');

      // ── Assert 3: overlay hides after the 600 ms post-success delay ─────
      await expect(overlay).toBeHidden({ timeout: 5_000 });

      // ── Assert 4: auth screen is gone, driver app is now the active view ─
      await expect(page.locator('#auth-screen')).toBeHidden({ timeout: 3_000 });
      await expect(page.locator('#app')).toBeVisible({ timeout: 3_000 });

      // ── Assert 5: pending-approval card is rendered ──────────────────────
      // bootApp() sets #pending-card display:block synchronously when
      // user.accountStatus === 'pending'.  The daily-fee modal (position:fixed,
      // z-index:3000) may visually cover it, so we check computed style rather
      // than Playwright's full visibility check.
      const pendingCardDisplay = await page.locator('#pending-card').evaluate(
        (el) => window.getComputedStyle(el).display
      );
      expect(pendingCardDisplay).not.toBe('none');

      const pendingCardTitle = await page.locator('.pending-card-title').evaluate(
        (el) => el.textContent
      );
      expect(pendingCardTitle).toContain('Documents Under Admin Review');
    }
  );

  // ---------------------------------------------------------------------------
  test(
    'upload overlay remains visible during transfer, then hides on success',
    async ({ page }) => {
      // Use a longer hold so we can assert the in-flight state explicitly.
      await page.unroute('**/api/auth/register');
      await page.route('**/api/auth/register', async (route) => {
        await new Promise((r) => setTimeout(r, 1_500));   // 1.5 s hold
        await route.fulfill({
          status: 201,
          contentType: 'application/json',
          body: JSON.stringify({
            ...MOCK_REGISTER_RESPONSE,
            user: { ...MOCK_REGISTER_RESPONSE.user, phone: '+923001234998' },
          }),
        });
      });

      await fillStep1(page, { phone: '+923001234998' });
      await uploadPhotos(page);
      await page.locator('#reg-submit-btn').click();

      // Overlay must appear immediately (showUploadProgress() is synchronous
      // inside doRegister(), called before the XHR is even sent).
      await expect(page.locator('#upload-progress-screen')).toBeVisible({ timeout: 8_000 });

      // After the 1.5 s server delay + 600 ms post-success timeout, it hides.
      await expect(page.locator('#upload-progress-screen')).toBeHidden({ timeout: 15_000 });

      // Driver app is the active screen.
      await expect(page.locator('#auth-screen')).toBeHidden();
      await expect(page.locator('#app')).toBeVisible();

      // pending-approval card is rendered in the DOM.
      const pendingCardDisplay = await page.locator('#pending-card').evaluate(
        (el) => window.getComputedStyle(el).display
      );
      expect(pendingCardDisplay).not.toBe('none');
    }
  );
});

// ── Registration failure tests ────────────────────────────────────────────────

test.describe('Registration failures — 409 duplicate phone and network error', () => {
  /**
   * Sets up all the standard stub routes except /api/auth/register so each
   * test can install its own register handler.
   */
  async function setupRoutesWithoutRegister(page) {
    await page.route('**/socket.io/**', (route) => {
      if (route.request().url().endsWith('.js')) {
        route.continue();
      } else {
        route.abort();
      }
    });
    await page.route('**/api/auth/me', (route) =>
      route.fulfill({ status: 401, contentType: 'application/json', body: '{"error":"unauthorized"}' })
    );
    await page.route('**/api/wallet**', (route) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: '{"balance":0,"transactions":[]}' })
    );
    await page.route('**/api/rides/my**', (route) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: '[]' })
    );
    await page.route('**/api/settings/payment**', (route) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: '{"accounts":{}}' })
    );
    await page.route('**/api/support/**', (route) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: '[]' })
    );
  }

  // ---------------------------------------------------------------------------
  test(
    '409 duplicate phone — overlay hides and error message appears in #auth-error',
    async ({ page }) => {
      await setupRoutesWithoutRegister(page);

      // Register endpoint returns 409 with a descriptive error body.
      await page.route('**/api/auth/register', async (route) => {
        await new Promise((r) => setTimeout(r, 100));
        await route.fulfill({
          status: 409,
          contentType: 'application/json',
          body: JSON.stringify({ error: 'Phone number already registered' }),
        });
      });

      await page.goto('/driver');
      await fillStep1(page);
      await uploadPhotos(page);
      await page.locator('#reg-submit-btn').click();

      // Overlay should appear while the request is in-flight…
      const overlay = page.locator('#upload-progress-screen');
      await expect(overlay).toBeVisible({ timeout: 8_000 });

      // …then hide once the 409 is received (no 600 ms success delay).
      await expect(overlay).toBeHidden({ timeout: 8_000 });

      // Auth screen must still be visible (driver was NOT logged in).
      await expect(page.locator('#auth-screen')).toBeVisible();
      await expect(page.locator('#app')).toBeHidden();

      // The exact server error message must appear in #auth-error.
      await expect(page.locator('#auth-error')).toHaveText(
        'Phone number already registered',
        { timeout: 3_000 }
      );
    }
  );

  // ---------------------------------------------------------------------------
  test(
    'network failure — overlay hides and network error message appears in #auth-error',
    async ({ page }) => {
      await setupRoutesWithoutRegister(page);

      // Abort the connection to simulate a network drop / offline condition.
      // A small delay lets the overlay appear before onerror fires so we can
      // assert the in-flight state reliably.
      await page.route('**/api/auth/register', async (route) => {
        await new Promise((r) => setTimeout(r, 200));
        await route.abort('failed');
      });

      await page.goto('/driver');
      await fillStep1(page);
      await uploadPhotos(page);
      await page.locator('#reg-submit-btn').click();

      // Overlay should appear while the XHR is in-flight…
      const overlay = page.locator('#upload-progress-screen');
      await expect(overlay).toBeVisible({ timeout: 8_000 });

      // …then hide once xhr.onerror fires.
      await expect(overlay).toBeHidden({ timeout: 8_000 });

      // Auth screen must still be visible (driver was NOT logged in).
      await expect(page.locator('#auth-screen')).toBeVisible();
      await expect(page.locator('#app')).toBeHidden();

      // A network-specific message must appear in #auth-error.
      await expect(page.locator('#auth-error')).toHaveText(
        'Network error — check your connection',
        { timeout: 3_000 }
      );
    }
  );
});
