// @ts-check
/**
 * E2E test: driver registration document upload flow with large photos
 *
 * Verifies that the XHR-based doRegister() path:
 *   1. Shows the #upload-progress-screen overlay
 *   2. Advances the progress bar to 100 %
 *   3. Hides the overlay after the server responds
 *   4. Shows the driver app (#app visible, #auth-screen hidden)
 *   5. Shows the pending-approval card (new drivers always get accountStatus:'pending')
 *
 * POST /api/auth/register is intercepted so the test is fully self-contained —
 * no MongoDB credentials are required.  The server must be reachable to serve
 * driver.html and its assets (playwright.config.js starts it automatically).
 *
 * Run:  cd ride-hailing && npx playwright test
 */

const { test, expect } = require('@playwright/test');
const http = require('http');
const path = require('path');

// ── Slow-chunked HTTP helper ───────────────────────────────────────────────────
/**
 * Sends `bodyStr` as an HTTP POST to localhost:port/path using real TCP chunks
 * so the server's body-parser must consume them over time — faithfully simulating
 * a driver on a slow mobile connection.
 *
 * Each `chunkSize`-byte slice is written after `delayMs` ms, then we wait for
 * the full HTTP response and return { status, body }.
 *
 * Any HTTP status (201 created, 409 duplicate, 500 DB unavailable) means the
 * server kept the connection alive and received the complete body without timing
 * out.  A connection error or socket reset would throw, failing the test.
 *
 * @param {number} port
 * @param {string} urlPath
 * @param {string} bodyStr
 * @param {{ chunkSize?: number, delayMs?: number }} [opts]
 * @returns {Promise<{ status: number, body: string, bodyBytesReceived: number }>}
 */
function sendSlowChunked(port, urlPath, bodyStr, { chunkSize = 4096, delayMs = 50 } = {}) {
  return new Promise((resolve, reject) => {
    const buf = Buffer.from(bodyStr, 'utf8');
    let settled = false;

    const req = http.request(
      {
        host: '127.0.0.1',
        port,
        path: urlPath,
        method: 'POST',
        headers: {
          'Content-Type':   'application/json',
          'Content-Length': buf.length,
        },
      },
      (res) => {
        let raw = '';
        res.on('data', (d) => (raw += d));
        res.on('end', () => {
          if (settled) return;
          settled = true;
          resolve({ status: res.statusCode, body: raw, bodyBytesReceived: buf.length });
        });
      }
    );

    // When the server enforces requestTimeout it sends 408 and destroys the
    // socket mid-transfer.  Subsequent write() calls produce an ECONNRESET.
    // We ignore those errors if the response was already captured above.
    req.on('error', (err) => {
      if (!settled) { settled = true; reject(err); }
    });

    // Stream body in chunks with artificial delays between each write.
    let offset = 0;
    const tick = () => {
      if (settled) return;   // response already received — stop sending
      if (offset >= buf.length) { req.end(); return; }
      req.write(buf.slice(offset, Math.min(offset + chunkSize, buf.length)));
      offset += chunkSize;
      setTimeout(tick, delayMs);
    };
    tick();
  });
}

// ── Test fixtures ─────────────────────────────────────────────────────────────
// Large plasma-fractal JPEGs (~1.7 MB each) generated by:
//   magick -size 2500x1900 plasma:fractal -quality 92 <name>.jpg
const FIXTURES = {
  profile:   path.join(__dirname, 'fixtures', 'profile.jpg'),
  license:   path.join(__dirname, 'fixtures', 'license.jpg'),
  cnicFront: path.join(__dirname, 'fixtures', 'cnic-front.jpg'),
  cnicBack:  path.join(__dirname, 'fixtures', 'cnic-back.jpg'),
};

// ── Mock registration response ────────────────────────────────────────────────
// Mimics the shape returned by POST /api/auth/register so that saveSession()
// and bootApp() run exactly as they would with a real server response.
const MOCK_REGISTER_RESPONSE = {
  token: [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',
    'eyJpZCI6IjY2MDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsInJvbGUiOiJkcml2ZXIiLCJuYW1lIjoiVGVzdCBEcml2ZXIifQ',
    'FAKESIGNATURE',
  ].join('.'),
  sessionToken: 'fakesessiontoken1234567890abcdef',
  user: {
    id:            '660000000000000000000000',
    name:          'Test Driver',
    email:         '',
    phone:         '+923001234999',
    role:          'driver',
    accountStatus: 'pending',   // new drivers always start as pending
    vehicleType:   'Car Mini',
    vehicleModel:  'Suzuki Cultus 2020',
    vehiclePlate:  'LHR-9999',
    lastDailyFeePaidAt: null,
    dailyFeeAmount: 200,
  },
};

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Intercept the register API and silence unrelated boot-time requests.
 *
 * IMPORTANT: the socket.io *client JS file* must load so that `io` is defined
 * when connectSocket() runs inside bootApp().  Only socket.io connection/
 * polling requests are aborted.
 */
async function setupRoutes(page, delay = 250) {
  await page.route('**/api/auth/register', async (route) => {
    await new Promise((r) => setTimeout(r, delay));
    await route.fulfill({
      status: 201,
      contentType: 'application/json',
      body: JSON.stringify(MOCK_REGISTER_RESPONSE),
    });
  });

  // Allow the socket.io *script* to load; abort only connection requests.
  await page.route('**/socket.io/**', (route) => {
    if (route.request().url().endsWith('.js')) {
      route.continue();
    } else {
      route.abort();   // server will also reject the fake JWT on connect_error
    }
  });

  // Stub boot-time API calls so they resolve cleanly without touching the DB.
  await page.route('**/api/auth/me', (route) =>
    route.fulfill({ status: 401, contentType: 'application/json', body: '{"error":"unauthorized"}' })
  );
  await page.route('**/api/wallet**', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: '{"balance":0,"transactions":[]}' })
  );
  await page.route('**/api/rides/my**', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: '[]' })
  );
  await page.route('**/api/settings/payment**', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: '{"accounts":{}}' })
  );
  await page.route('**/api/support/**', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: '[]' })
  );
}

/** Fill Step 1 of the registration form and advance to Step 2. */
async function fillStep1(page, { phone = '+923001234999' } = {}) {
  await page.getByRole('button', { name: 'Register' }).click();
  await expect(page.locator('#register-form')).toBeVisible();

  await page.locator('#r-name').fill('Test Driver');
  await page.locator('#r-phone').fill(phone);
  await page.locator('#r-pass').fill('password123');
  await page.locator('#r-vehicle').selectOption('Car Mini');
  await page.locator('#r-vehicle-model').fill('Suzuki Cultus 2020');
  await page.locator('#r-plate').fill('LHR-9999');

  await page.getByRole('button', { name: /Continue.*Upload Documents/i }).click();
  await expect(page.locator('#reg-step2')).toBeVisible();
}

/** Attach the four large test-fixture photos to the file inputs. */
async function uploadPhotos(page) {
  await page.locator('#r-profile-photo').setInputFiles(FIXTURES.profile);
  await page.locator('#r-license-photo').setInputFiles(FIXTURES.license);
  await page.locator('#r-cnic-front').setInputFiles(FIXTURES.cnicFront);
  await page.locator('#r-cnic-back').setInputFiles(FIXTURES.cnicBack);
}

// ── Tests ─────────────────────────────────────────────────────────────────────

test.describe('Document upload flow — large photos (~1.7 MB each)', () => {
  test.beforeEach(async ({ page }) => {
    await setupRoutes(page);
    await page.goto('/driver');
  });

  // ---------------------------------------------------------------------------
  test(
    'upload progress overlay appears, reaches 100 %, hides, and driver app loads',
    async ({ page }) => {
      await fillStep1(page);
      await uploadPhotos(page);

      // ── Submit ──────────────────────────────────────────────────────────
      await page.locator('#reg-submit-btn').click();

      // ── Assert 1: upload-progress overlay becomes visible ───────────────
      const overlay = page.locator('#upload-progress-screen');
      await expect(overlay).toBeVisible({ timeout: 8_000 });

      // ── Assert 2: progress bar reaches 100 % ────────────────────────────
      // xhr.onload sets the bar to 100 % on a 2xx response.
      await expect(page.locator('#upload-progress-pct')).toHaveText('100%', { timeout: 15_000 });

      const barWidth = await page.locator('#upload-progress-bar').evaluate(
        (el) => el.style.width
      );
      expect(barWidth).toBe('100%');

      // ── Assert 3: overlay hides after the 600 ms post-success delay ─────
      await expect(overlay).toBeHidden({ timeout: 5_000 });

      // ── Assert 4: auth screen is gone, driver app is now the active view ─
      await expect(page.locator('#auth-screen')).toBeHidden({ timeout: 3_000 });
      await expect(page.locator('#app')).toBeVisible({ timeout: 3_000 });

      // ── Assert 5: pending-approval card is rendered ──────────────────────
      // bootApp() sets #pending-card display:block synchronously when
      // user.accountStatus === 'pending'.  The daily-fee modal (position:fixed,
      // z-index:3000) may visually cover it, so we check computed style rather
      // than Playwright's full visibility check.
      const pendingCardDisplay = await page.locator('#pending-card').evaluate(
        (el) => window.getComputedStyle(el).display
      );
      expect(pendingCardDisplay).not.toBe('none');

      const pendingCardTitle = await page.locator('.pending-card-title').evaluate(
        (el) => el.textContent
      );
      expect(pendingCardTitle).toContain('Documents Under Admin Review');
    }
  );

  // ---------------------------------------------------------------------------
  test(
    'upload overlay remains visible during transfer, then hides on success',
    async ({ page }) => {
      // Use a longer hold so we can assert the in-flight state explicitly.
      await page.unroute('**/api/auth/register');
      await page.route('**/api/auth/register', async (route) => {
        await new Promise((r) => setTimeout(r, 1_500));   // 1.5 s hold
        await route.fulfill({
          status: 201,
          contentType: 'application/json',
          body: JSON.stringify({
            ...MOCK_REGISTER_RESPONSE,
            user: { ...MOCK_REGISTER_RESPONSE.user, phone: '+923001234998' },
          }),
        });
      });

      await fillStep1(page, { phone: '+923001234998' });
      await uploadPhotos(page);
      await page.locator('#reg-submit-btn').click();

      // Overlay must appear immediately (showUploadProgress() is synchronous
      // inside doRegister(), called before the XHR is even sent).
      await expect(page.locator('#upload-progress-screen')).toBeVisible({ timeout: 8_000 });

      // After the 1.5 s server delay + 600 ms post-success timeout, it hides.
      await expect(page.locator('#upload-progress-screen')).toBeHidden({ timeout: 15_000 });

      // Driver app is the active screen.
      await expect(page.locator('#auth-screen')).toBeHidden();
      await expect(page.locator('#app')).toBeVisible();

      // pending-approval card is rendered in the DOM.
      const pendingCardDisplay = await page.locator('#pending-card').evaluate(
        (el) => window.getComputedStyle(el).display
      );
      expect(pendingCardDisplay).not.toBe('none');
    }
  );
});

// ── Slow-network tests ────────────────────────────────────────────────────────

test.describe('Upload progress UI — progress bar advances and overlay hides correctly', () => {
  /**
   * Verifies the client-side progress bar DOM behaviour when upload.progress
   * events fire mid-flight.
   *
   * Background: CDP Network.emulateNetworkConditions throttles at the real
   * socket layer, but Playwright's page.route() intercepts requests before they
   * reach the network socket — so xhr.upload.progress never fires naturally for
   * mocked routes.  To exercise the UI handler in isolation we monkey-patch
   * XMLHttpRequest.prototype.send to dispatch five synthetic ProgressEvents
   * (20 %, 40 %, 60 %, 80 %, 95 % of the real body size) spread over 1.5 s.
   * The route mock holds for 4 s, so these events land before xhr.onload fires.
   *
   * This test covers client UI behaviour only.  For server-side slow-upload
   * reliability see the "Slow-socket upload" suite below.
   */
  test(
    'synthetic upload events advance the progress bar from 0 % to 100 %',
    async ({ page }) => {
      test.setTimeout(60_000);

      // ── 1. Inject the XHR shim BEFORE page load ───────────────────────
      // addInitScript() runs the function in the page context on every
      // navigation, before any page scripts execute.
      await page.addInitScript(() => {
        const _realSend = XMLHttpRequest.prototype.send;
        XMLHttpRequest.prototype.send = function (body) {
          const upload = this.upload;
          // Measure the serialised body so progress ratios are realistic.
          const total = body ? new Blob([body]).size : 1;
          // Fire 5 synthetic progress events spread across 1.5 s.
          [0.2, 0.4, 0.6, 0.8, 0.95].forEach((ratio, i) => {
            setTimeout(() => {
              upload.dispatchEvent(
                new ProgressEvent('progress', {
                  bubbles: false,
                  lengthComputable: true,
                  loaded: Math.floor(ratio * total),
                  total,
                })
              );
            }, (i + 1) * 300); // 300 ms, 600 ms, 900 ms, 1 200 ms, 1 500 ms
          });
          _realSend.call(this, body);
        };
      });

      // ── 2. Register stub routes; hold the register response for 4 s ───
      await setupRoutes(page, 4_000);
      await page.goto('/driver');

      await fillStep1(page, { phone: '+923001234996' });
      await uploadPhotos(page);
      await page.locator('#reg-submit-btn').click();

      // ── Assert 1: upload-progress overlay appears ─────────────────────
      const overlay = page.locator('#upload-progress-screen');
      await expect(overlay).toBeVisible({ timeout: 10_000 });

      // ── Assert 2: progress bar advances past 0 % BEFORE upload ends ───
      // The first synthetic event fires at ~300 ms after send(); the route
      // mock holds the response for 4 s, so there is a clear window where
      // pct is in the range (0, 100).
      await page.waitForFunction(
        () => {
          const el = document.querySelector('#upload-progress-pct');
          if (!el) return false;
          const pct = parseInt(el.textContent, 10);
          return !isNaN(pct) && pct > 0 && pct < 100;
        },
        { timeout: 15_000 }
      );

      // Snapshot the mid-flight value — it must be strictly positive.
      const midPct = await page.locator('#upload-progress-pct').evaluate(
        (el) => parseInt(el.textContent, 10)
      );
      expect(midPct).toBeGreaterThan(0);

      // ── Assert 3: progress bar reaches 100 % once the response lands ──
      await expect(page.locator('#upload-progress-pct')).toHaveText('100%', {
        timeout: 15_000,
      });
      expect(
        await page.locator('#upload-progress-bar').evaluate(
          (el) => el.style.width
        )
      ).toBe('100%');

      // ── Assert 4: overlay hides after the 600 ms post-success delay ───
      await expect(overlay).toBeHidden({ timeout: 5_000 });

      // ── Assert 5: driver app is the active screen ─────────────────────
      await expect(page.locator('#auth-screen')).toBeHidden({ timeout: 5_000 });
      await expect(page.locator('#app')).toBeVisible({ timeout: 5_000 });

      // ── Assert 6: pending-approval card is rendered in the DOM ────────
      const pendingCardDisplay = await page.locator('#pending-card').evaluate(
        (el) => window.getComputedStyle(el).display
      );
      expect(pendingCardDisplay).not.toBe('none');
    }
  );
});

// ── Slow-socket integration tests ─────────────────────────────────────────────

/**
 * Shared JSON body for the slow-socket tests.
 * Mirrors a real doRegister() payload: four 25 000-char base64 image fields
 * ≈ four ~18 KB compressed photos ≈ ~100 KB total.
 */
const SLOW_UPLOAD_BODY = JSON.stringify({
  name:         'Slow Upload Driver',
  phone:        '+923009999000',
  password:     'password123',
  role:         'driver',
  vehicleType:  'Car Mini',
  vehicleModel: 'Toyota Corolla 2022',
  vehiclePlate: 'TEST-SLW',
  profilePhoto: 'data:image/jpeg;base64,' + 'A'.repeat(25_000),
  licensePhoto: 'data:image/jpeg;base64,' + 'B'.repeat(25_000),
  cnicFront:    'data:image/jpeg;base64,' + 'C'.repeat(25_000),
  cnicBack:     'data:image/jpeg;base64,' + 'D'.repeat(25_000),
});

// ── Real-server slow-upload test ──────────────────────────────────────────────

test.describe('Slow-socket upload — live server accepts slow continuous body within configured timeout', () => {
  /**
   * Context
   * -------
   * server.requestTimeout controls how long the http.Server allows for a
   * request to be received.  The default (Node 18+: 300 000 ms) is sufficient
   * for slow mobile uploads but is left implicit and can be overridden
   * accidentally by a framework upgrade or misconfiguration to a value too
   * short for 2G/3G uploads.
   *
   * The server now sets server.requestTimeout explicitly to 600 000 ms and
   * exposes it via REQUEST_TIMEOUT_MS.  playwright.config.js sets
   * REQUEST_TIMEOUT_MS=8 000 ms so tests use an 8 s budget.
   *
   * What this test proves
   * ---------------------
   * A ~100 KB body streamed in 4 KB chunks with 160 ms gaps takes roughly
   * 4 s — a duration that would be rejected by any timeout set below ~4 s
   * (the "formerly too-short" threshold).  The test sends this body to the
   * real /api/auth/register endpoint and asserts any HTTP response arrives,
   * confirming the server held the TCP connection open and received the
   * complete body within the 8 s configured budget.
   *
   * A socket error (ECONNRESET / ETIMEDOUT) or zero-byte body would mean the
   * server dropped the slow upload — the test would throw/fail.
   */

  test(
    'slow ~4 s upload of ~100 KB body succeeds — server holds connection open within the configured 8 s budget',
    async () => {
      test.setTimeout(25_000);

      // 25 chunks × 160 ms ≈ 4 000 ms  — crosses a sub-4 s "formerly too-short"
      // threshold but stays within the configured 8 000 ms test-mode budget.
      const { status, bodyBytesReceived } = await sendSlowChunked(
        3000,
        '/api/auth/register',
        SLOW_UPLOAD_BODY,
        { chunkSize: 4_096, delayMs: 160 }
      );

      // The server must have received the full body before replying.
      expect(bodyBytesReceived).toBe(Buffer.byteLength(SLOW_UPLOAD_BODY));

      // Any HTTP status proves the server kept the connection alive.
      // 201 = registration success, 409 = duplicate phone, 500 = DB unavailable.
      expect([201, 409, 500]).toContain(status);
    }
  );
});

// ── Registration failure tests ────────────────────────────────────────────────

test.describe('Registration failures — 409 duplicate phone and network error', () => {
  /**
   * Sets up all the standard stub routes except /api/auth/register so each
   * test can install its own register handler.
   */
  async function setupRoutesWithoutRegister(page) {
    await page.route('**/socket.io/**', (route) => {
      if (route.request().url().endsWith('.js')) {
        route.continue();
      } else {
        route.abort();
      }
    });
    await page.route('**/api/auth/me', (route) =>
      route.fulfill({ status: 401, contentType: 'application/json', body: '{"error":"unauthorized"}' })
    );
    await page.route('**/api/wallet**', (route) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: '{"balance":0,"transactions":[]}' })
    );
    await page.route('**/api/rides/my**', (route) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: '[]' })
    );
    await page.route('**/api/settings/payment**', (route) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: '{"accounts":{}}' })
    );
    await page.route('**/api/support/**', (route) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: '[]' })
    );
  }

  // ---------------------------------------------------------------------------
  test(
    '409 duplicate phone — overlay hides and error message appears in #auth-error',
    async ({ page }) => {
      await setupRoutesWithoutRegister(page);

      // Register endpoint returns 409 with a descriptive error body.
      await page.route('**/api/auth/register', async (route) => {
        await new Promise((r) => setTimeout(r, 100));
        await route.fulfill({
          status: 409,
          contentType: 'application/json',
          body: JSON.stringify({ error: 'Phone number already registered' }),
        });
      });

      await page.goto('/driver');
      await fillStep1(page);
      await uploadPhotos(page);
      await page.locator('#reg-submit-btn').click();

      // Overlay should appear while the request is in-flight…
      const overlay = page.locator('#upload-progress-screen');
      await expect(overlay).toBeVisible({ timeout: 8_000 });

      // …then hide once the 409 is received (no 600 ms success delay).
      await expect(overlay).toBeHidden({ timeout: 8_000 });

      // Auth screen must still be visible (driver was NOT logged in).
      await expect(page.locator('#auth-screen')).toBeVisible();
      await expect(page.locator('#app')).toBeHidden();

      // The exact server error message must appear in #auth-error.
      await expect(page.locator('#auth-error')).toHaveText(
        'Phone number already registered',
        { timeout: 3_000 }
      );
    }
  );

  // ---------------------------------------------------------------------------
  test(
    'network failure — overlay hides and network error message appears in #auth-error',
    async ({ page }) => {
      await setupRoutesWithoutRegister(page);

      // Abort the connection to simulate a network drop / offline condition.
      // A small delay lets the overlay appear before onerror fires so we can
      // assert the in-flight state reliably.
      await page.route('**/api/auth/register', async (route) => {
        await new Promise((r) => setTimeout(r, 200));
        await route.abort('failed');
      });

      await page.goto('/driver');
      await fillStep1(page);
      await uploadPhotos(page);
      await page.locator('#reg-submit-btn').click();

      // Overlay should appear while the XHR is in-flight…
      const overlay = page.locator('#upload-progress-screen');
      await expect(overlay).toBeVisible({ timeout: 8_000 });

      // …then hide once xhr.onerror fires.
      await expect(overlay).toBeHidden({ timeout: 8_000 });

      // Auth screen must still be visible (driver was NOT logged in).
      await expect(page.locator('#auth-screen')).toBeVisible();
      await expect(page.locator('#app')).toBeHidden();

      // A network-specific message must appear in #auth-error.
      await expect(page.locator('#auth-error')).toHaveText(
        'Network error — check your connection',
        { timeout: 3_000 }
      );
    }
  );
});
